version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
